const PDFDocument = require("pdfkit");

function generateQuizResultPdf(resultData) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks = [];

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const { judgeFullName, courtName, jurisdiction, matchScore, resultLabel, matchExplanation, keyStats } = resultData;

    doc
      .fontSize(10)
      .fillColor("#888888")
      .text("JudgeTracker.info — Quiz Result", { align: "center" });

    doc.moveDown(0.5);
    doc
      .moveTo(50, doc.y)
      .lineTo(545, doc.y)
      .strokeColor("#cccccc")
      .stroke();
    doc.moveDown(1);

    doc
      .fontSize(22)
      .fillColor("#1a1a2e")
      .text("Your Judicial Match", { align: "center" });

    doc.moveDown(0.5);

    doc
      .fontSize(18)
      .fillColor("#2563eb")
      .text(judgeFullName || "Unknown Judge", { align: "center" });

    if (courtName || jurisdiction) {
      doc.moveDown(0.25);
      doc
        .fontSize(11)
        .fillColor("#555555")
        .text([courtName, jurisdiction].filter(Boolean).join(" · "), { align: "center" });
    }

    if (matchScore !== undefined && matchScore !== null) {
      doc.moveDown(0.5);
      doc
        .fontSize(13)
        .fillColor("#16a34a")
        .text(`Match Score: ${matchScore}`, { align: "center" });
    }

    if (resultLabel) {
      doc.moveDown(0.25);
      doc
        .fontSize(12)
        .fillColor("#374151")
        .text(`Result: ${resultLabel}`, { align: "center" });
    }

    doc.moveDown(1);
    doc
      .moveTo(50, doc.y)
      .lineTo(545, doc.y)
      .strokeColor("#e5e7eb")
      .stroke();
    doc.moveDown(0.75);

    doc
      .fontSize(14)
      .fillColor("#1a1a2e")
      .text("Why You Matched", { underline: true });
    doc.moveDown(0.5);

    if (matchExplanation && Array.isArray(matchExplanation) && matchExplanation.length > 0) {
      matchExplanation.forEach((item) => {
        doc
          .fontSize(11)
          .fillColor("#374151")
          .text(`• ${item}`, { indent: 10 });
        doc.moveDown(0.25);
      });
    } else if (matchExplanation && typeof matchExplanation === "string") {
      doc
        .fontSize(11)
        .fillColor("#374151")
        .text(matchExplanation, { indent: 10 });
    } else {
      doc
        .fontSize(11)
        .fillColor("#6b7280")
        .text("Based on your quiz choices, your judicial instincts align with this judge's patterns.", { indent: 10 });
    }

    if (keyStats && typeof keyStats === "object" && Object.keys(keyStats).length > 0) {
      doc.moveDown(0.75);
      doc
        .moveTo(50, doc.y)
        .lineTo(545, doc.y)
        .strokeColor("#e5e7eb")
        .stroke();
      doc.moveDown(0.75);

      doc
        .fontSize(14)
        .fillColor("#1a1a2e")
        .text("Judge Key Stats", { underline: true });
      doc.moveDown(0.5);

      Object.entries(keyStats).forEach(([key, value]) => {
        doc
          .fontSize(11)
          .fillColor("#374151")
          .text(`${key}: `, { continued: true })
          .fillColor("#1a1a2e")
          .text(String(value));
        doc.moveDown(0.2);
      });
    }

    const pageHeight = doc.page.height;
    const footerY = pageHeight - 60;
    doc
      .moveTo(50, footerY)
      .lineTo(545, footerY)
      .strokeColor("#cccccc")
      .stroke();

    doc
      .fontSize(9)
      .fillColor("#9ca3af")
      .text(
        "Generated by JudgeTracker.info — For informational purposes only. Not legal advice.",
        50,
        footerY + 10,
        { align: "center", width: 495 }
      );

    doc.end();
  });
}

module.exports = { generateQuizResultPdf };
